# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.ssh.username = "docker"
  config.ssh.password = "tcuser"
  
  # Exposing certificates for the docker client
  config.vm.synced_folder ".", "/vagrant"

  config.vm.box = "mylinuxcontainerhost"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "mylinuxcontainerhost"
  end

  config.vm.provision "shell",
    inline: "sudo cp -r /var/lib/boot2docker/tls /vagrant",
    run: "always",
    privileged: true
end
